### ISSUE TITLE
Upgrade Color Scheme and Branding

### ISSUE THREAD

**Issue by csell5** [ThatConference/SlackSignupWebsite#29]
This year we upgraded our color scheme and branding. This should be upgraded to match thatconference.com (https://github.com/thatconference/that-website)

**Comment by r-andrew-dev** [comment]
Interested in this issue!

**Comment by LuizHAP** [comment]
I'm also interested, is it possible?

**Comment by csell5** [comment]
@LuizHAP @r-andrew-dev snatched it.. but there are others here I can label up.
